### ISSUE TITLE
Suggestions only

### ISSUE THREAD

**Issue by thomas52** [mnoorenberghe/webtrees-facebook#19]
Matt: The 'regular' User Admin page shows "Date Registered" & "Last Logged In" - it also shows a setting for "Default Individual" & "Individual Record," and a link on the individual page to the user.  I would like to be able to determine the last time a user logged in, and I would like to see a link on the individual page similar to what we have now for user accounts: 'Name' - 'Username'.  Thanks for your contribution. - tom adkins
![screenshot_1](https://cloud.githubusercontent.com/assets/11645978/6822811/e0114aac-d2b8-11e4-8763-85487596385d.jpg)

**Comment by mnoorenberghe** [comment]
Hi @thomas52, apologies for the long delay. I'm not exactly sure what you're asking for… the Facebook login integration does update the regular User Admin table which still applies to users who login via Facebook. The username shown on the individual page would also be the username auto-chosen upon first FB login. Could you clarify what you're wanting?

**Comment by thomas52** [comment]
Nope; I have no clue, been too long.

**Comment by mnoorenberghe** [comment]
ok, sorry :(
