### ISSUE TITLE
PHP Fatal error: Class 'WT_Module' not found in module.php

### ISSUE THREAD

**Issue by nmella** [mnoorenberghe/webtrees-facebook#21]
Hi There,

Maybe this is a simple fix. I am not a developer ... appreciate any help.

I have a Webtrees install 1.7.8 on a Linux server with PHP7. After installing the Facebook Integration module version v1.0-beta.7, I get the following error when trying to enable the module in Adminstration => Modules:

PHP Fatal error: Class 'WT_Module' not found in /home/petacl/mella.cl/modules_v3/facebook/module.php on line 31

Any solution around this ? I have a standward webtrees installation without any customizations. 

Thanks,

Nicolás

**Comment by Ephemerality** [comment]
If you're still trying to get it going, you can check out my pull request (#22) which contains updates for the newer versions of webtrees.

**Comment by mnoorenberghe** [comment]
This should be fixed by #23 which adds 1.7.9 support
