### ISSUE TITLE
Webtrees module admin page broken after installing

### ISSUE THREAD

**Issue by Meltz014** [mnoorenberghe/webtrees-facebook#26]
I followed the instructions to install the facebook module to my webtrees site, but the modules admin page is now broken, i'm wondering if there is a missing dependancy not enabled or something.  My Webtrees version is 1.7.11, using php 7.0

**Comment by mnoorenberghe** [comment]
Are you using the latest code from GitHub or what version?

**Comment by Meltz014** [comment]
I'm using the latest release from GitHub. Should I just clone the master
branch?

**Comment by mnoorenberghe** [comment]
You need to clone master as only it supports 1.7. If it works let me know and I can maybe do a release… I had assumed that 1.8 would get released a long time ago and was waiting for that but I guess that was a mistake.

**Comment by mnoorenberghe** [comment]
Ooh, I just realized that 1.7.10 and 1.7.11 were released this month and I haven't tested with them so it may still not work.
